version: '2'

services:

    nginx:
        container_name: dev_nginx
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        volumes:
            - ../../../:/var/www
            - ../../../storage/app/public:/var/www/public/storage
        ports:
            - "8080:80"
        links:
            - php
        mem_limit: 64000000
        memswap_limit: 128000000

    php:
        container_name: dev_php
        build:
            context: ./php/
            dockerfile: Dockerfile
        volumes:
            - ../../../:/var/www
            - ../../../storage/app/public:/var/www/public/storage
        environment:
            - "DB_HOST=mysql"
            - "DB_PORT=3306"
            - "REDIS_HOST=redis"
            - "REDIS_PASSWORD=null"
            - "REDIS_PORT=6379"
        links:
            - mysql
            - redis
        mem_limit: 128000000
        memswap_limit: 256000000

    mysql:
        container_name: dev_mysql
        build:
            context: ./mysql/
            dockerfile: Dockerfile
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ../../../mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
        mem_limit: 512000000
        memswap_limit: 1024000000

    redis:
        container_name: dev_redis
        build:
            context: ./redis/
            dockerfile: Dockerfile
        ports:
            - "6379:6379"

    socket:
        container_name: dev_node
        build:
            context: ./node/
            dockerfile: Dockerfile
        volumes:
            - ../../../socket-server:/socket-server
        links:
            - redis
        command: node /socket-server/server.js
        ports:
            - "3000:3000"